name: Deploy to Glitch
on:
  push:
    branches:
      - 'master'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Deploy this repo to Glitch.com
      - name: Deploy to Glitch
        run: echo "Implement this"